Data and scripts to make fig5, fig6, figS4d, figS6, figS7, tableS2, a…
broadinstitute/gnomad-mitochondria pull request #9
Opened 2021-06-29 16:42 UTC by niclak

…nd tableS3

2021-08-23 13:56 UTC, klaricch requested changes

2021-08-23 13:56 UTC, klaricch commented on manuscript_analyses/collate_Figure5.R
> +#compile figure panel
for all R scripts, doesn't need to be changed, but typically would add spaces around operators and after commas

2021-10-07 18:14 UTC, niclak commented on manuscript_analyses/final_data_files/insilicos/get_hmtvar.py
> +            annotation = output.read()
removed the new line in the write below to do this

2021-10-07 21:32 UTC, niclak commented on manuscript_analyses/reformat_vcf.py
> +        "-other_databases_path",
changed all to --

2021-10-07 21:47 UTC, niclak commented on manuscript_analyses/reformat_vcf.py
> +            if len(annotation) > 3:
thanks for the pointer - I've updated the code

2021-10-08 16:05 UTC, niclak commented on manuscript_analyses/reformat_vcf.py
> +                info = row[7]  # column 8
good idea - i've updated the code to do this

2021-10-08 17:03 UTC, niclak commented on manuscript_analyses/reformat_vcf.py
> +                        + str(matches_annotations[POS, REF, ALT, SYMBOL][0])
have updated to do this

2021-10-13 18:29 UTC, klaricch reviewed
just a few small things

2021-10-14 13:08 UTC, merged